# Generated by Django 5.2.13 on 2026-04-27 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nombre de ciudad')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['name_city'],
            },
        ),
        migrations.CreateModel(
            name='PriceBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_price', models.DecimalField(decimal_places=2, default=8000, max_digits=12, verbose_name='Precio de envio')),
                ('weight_price', models.DecimalField(decimal_places=2, default=450, max_digits=12, verbose_name='Precio por kilo')),
                ('volumetric_divider', models.IntegerField(default=4000, verbose_name='Divisor volumetrico')),
                ('update_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_province', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Nombre de provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['name_province'],
            },
        ),
        migrations.CreateModel(
            name='PendingShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso')),
                ('height', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Alto')),
                ('width', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ancho')),
                ('length', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Largo')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('shipment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='QuickShipApp.pendingshipment')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal de origen')),
                ('origin_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origen de paquete')),
                ('receiver', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del destinatario')),
                ('receiver_type_document', models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT/CUIL'), ('LIB', 'LIBRETA  UNICA')], default='DNI', max_length=20)),
                ('receiver_tax_condition', models.CharField(choices=[('CF', 'Consumidor Final'), ('MO', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('EX', 'Exento')], default='CF', max_length=20, verbose_name='Condición fiscal')),
                ('receiver_business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social')),
                ('receiver_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento del destinatario')),
                ('receiver_number_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de celular')),
                ('receiver_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico')),
                ('destination_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal')),
                ('destination_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio')),
                ('destination_extrainfo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información extra')),
                ('type_shipment', models.CharField(choices=[('SUCURSAL', 'SUCURSAL'), ('DOMICILIO', 'DOMICILIO'), ('EXPRESS', 'EXPRESS')], default='SUCURSAL', max_length=60)),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QuickShipApp.city', verbose_name='Ciudad')),
                ('origin_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='origin_city', to='QuickShipApp.city', verbose_name='Ciudad de origen')),
                ('shipment_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='QuickShipApp.pendingshipment')),
                ('destination_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QuickShipApp.province', verbose_name='Provincia')),
                ('origin_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='origin_province', to='QuickShipApp.province', verbose_name='Provincia de origen')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='QuickShipApp.province'),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de factura')),
                ('tracking_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código de seguimiento')),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de envío')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetailShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción del producto')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Alto (cm)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ancho (cm)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Largo (cm)')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('weight_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio por peso/volumen')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('shipping_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_shipping', to='QuickShipApp.shipping')),
            ],
            options={
                'verbose_name': 'Detalle de Envío',
                'verbose_name_plural': 'Detalles de Envíos',
            },
        ),
        migrations.CreateModel(
            name='DataShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255, verbose_name='Nombre del remitente')),
                ('sender_type_document', models.CharField(choices=[('DNI', 'Documentos de identidad'), ('CUIT', 'CUIT/CUIL'), ('LIB', 'LIBRETA UNICA')], default='DNI', max_length=10, verbose_name='Tipo de documento del remitente')),
                ('sender_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento del remitente')),
                ('sender_tax_condition', models.CharField(choices=[('CF', 'Consumidor Final'), ('MO', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('EX', 'Exento')], default='CF', max_length=20, verbose_name='Condición fiscal del remitente')),
                ('sender_business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social del remitente')),
                ('sender_email', models.EmailField(max_length=255, verbose_name='Correo electrónico del remitente')),
                ('sender_number_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono del remitente')),
                ('origin_province', models.CharField(max_length=80, verbose_name='Provincia de origen')),
                ('origin_city', models.CharField(max_length=100, verbose_name='Ciudad de origen')),
                ('origin_zipcode', models.CharField(max_length=10, verbose_name='Código postal de origen')),
                ('origin_address', models.CharField(max_length=255, verbose_name='Dirección de origen')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='Nombre del destinatario')),
                ('receiver_type_document', models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT/CUIL'), ('LIB', 'LIBRETA UNICA')], default='DNI', max_length=20, verbose_name='Tipo de documento del destinatario')),
                ('receiver_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento del destinatario')),
                ('receiver_tax_condition', models.CharField(choices=[('CF', 'Consumidor Final'), ('MO', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('EX', 'Exento')], default='CF', max_length=20, verbose_name='Condición fiscal del destinatario')),
                ('receiver_business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social del destinatario')),
                ('receiver_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico del destinatario')),
                ('receiver_number_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono del destinatario')),
                ('destination_province', models.CharField(max_length=80, verbose_name='Provincia de destino')),
                ('destination_city', models.CharField(max_length=100, verbose_name='Ciudad de destino')),
                ('destination_zipcode', models.CharField(max_length=10, verbose_name='Código postal de destino')),
                ('destination_address', models.CharField(max_length=255, verbose_name='Dirección de destino')),
                ('destination_extra_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información extra de destino')),
                ('shipping_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_shipping', to='QuickShipApp.shipping')),
            ],
            options={
                'verbose_name': 'Datos de Envío',
                'verbose_name_plural': 'Datos de Envíos',
            },
        ),
        migrations.CreateModel(
            name='ShippingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'En Proceso'), ('IN_TRANSIT', 'En Tránsito'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado'), ('RETURNED', 'Devuelto')], default='PENDING', max_length=50, verbose_name='Estado del envío')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización de estado')),
                ('shipping_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='QuickShipApp.shipping')),
            ],
            options={
                'verbose_name': 'Estado de Envío',
                'verbose_name_plural': 'Estados de Envíos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('DNI', 'Documentos de identidad'), ('CUIT', 'CUIT/CUIL'), ('LIB', 'LIBRETA UNICA')], default='DNI', max_length=10, verbose_name='Tipo de documento')),
                ('document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento')),
                ('tax_condition', models.CharField(blank=True, choices=[('CF', 'Consumidor Final'), ('MO', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('EX', 'Exento')], default='CF', max_length=20, null=True, verbose_name='Condición IVA')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto')),
                ('zipcode', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código postal')),
                ('street_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle/Barrio')),
                ('street_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Altura/Número')),
                ('apartament', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento(opcional)')),
                ('extra_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información extra (opcional)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Usuario verificado')),
                ('city_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QuickShipApp.city', verbose_name='Ciudad/departamento')),
                ('province_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QuickShipApp.province', verbose_name='Provincia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
    ]
