# Generated by Django 5.2.13 on 2026-04-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickShipApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de envío'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio total'),
        ),
    ]
